pipelines:
  default:
    - step:
        name: CI Build
        image: node:8.6.0
        script:
          - npm install
  branches:
    stage:
      - step:
          name: Build
          image: node:8.6.0
          script:
            - npm install
            - npm run build:stage
          artifacts:
            - dist/**
      - step:
          name: Deploy to Staging
          image: python:3.5.1
          script:
            - pip install awscli
            - aws s3 sync dist/ S3_BUCKET_STAGING --delete
    master:
      - step:
          name: Build
          image: node:8.6.0
          script:
            - npm install
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy to Master
          image: python:3.5.1
          script:
            - pip install awscli
            - aws s3 sync dist/ S3_BUCKET_PRODUCTION --delete
