export const SHOW_MAIN_LOADING = 'SHOW_MAIN_LOADING'
export const HIDE_MAIN_LOADING = 'HIDE_MAIN_LOADING'

export const SET_MOVIES = 'SET_MOVIES'
export const SET_FAVORITES = 'SET_FAVORITES'
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES'
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES'